fix(shunit2): カラー出力指定時に、echo に-eが付かないパターンがある

diff --git a/test/ut/shunit2 b/test/ut/shunit2
--- a/test/ut/shunit2
+++ b/test/ut/shunit2
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 # vim:et:ft=sh:sts=2:sw=2
 #
 # Copyright 2008-2018 Kate Ward. All Rights Reserved.
@@ -30,13 +30,13 @@ SHUNIT_ERROR=2
 
 # Logging functions.
 _shunit_warn() {
-  echo "${__shunit_ansi_yellow}shunit2:WARN${__shunit_ansi_none} $*" >&2
+  echo -e "${__shunit_ansi_yellow}shunit2:WARN${__shunit_ansi_none} $*" >&2
 }
 _shunit_error() {
-  echo "${__shunit_ansi_red}shunit2:ERROR${__shunit_ansi_none} $*" >&2
+  echo -e "${__shunit_ansi_red}shunit2:ERROR${__shunit_ansi_none} $*" >&2
 }
 _shunit_fatal() {
-  echo "${__shunit_ansi_red}shunit2:FATAL${__shunit_ansi_none} $*" >&2
+  echo -e "${__shunit_ansi_red}shunit2:FATAL${__shunit_ansi_none} $*" >&2
   exit ${SHUNIT_ERROR}
 }
 
