refactor(webhook): functionの配置場所を整理

diff --git a/src/bin/lib/stfw_utils b/src/bin/lib/stfw_utils
--- a/src/bin/lib/stfw_utils
+++ b/src/bin/lib/stfw_utils
@@ -8,11 +8,11 @@
 #
 # 定義リスト
 #   stfw.apply_log_level
-#   stfw.apply_dynamic_env
+#   stfw.parse_log_level
 #   stfw.get_plugin_path
 #   stfw.get_passwd_path
 #   stfw.show_passwd
-#   stfw.list_bulk_exec_scripts
+#   stfw.list_files
 #   stfw.bulk_exec_scripts
 #   stfw.is_in_scenario-root-dir
 #   stfw.is_in_scenario-dir
@@ -23,7 +23,11 @@
 #   stfw.process.is_installed
 #   stfw.process.install
 #   stfw.get_digdag_version
+#   stfw.must_run_on_server
+#   stfw.is_run_on_server
+#   stfw.set_raw_params
 #   stfw.get_raw_params
+#   stfw.webhook.async_execute
 #
 #===================================================================================================
 #---------------------------------------------------------------------------------------------------
@@ -136,6 +140,13 @@ function stfw.get_plugin_path() {
   # プロジェクトplugin
   if [[ -d "${STFW_PROJ_DIR_PLUGIN}/${_plugin_name}" ]]; then
     _result="${STFW_PROJ_DIR_PLUGIN}/${_plugin_name}"
+  fi
+  if [[ "$(stfw.is_run_on_server)" = "true" ]]; then
+    # digdagでワークフロー実行中の場合、workspaceディレクトリになるので、実ディレクトリを明示
+    local _real_proj_plugin_dir="${STFW_PROJ_DIR//\/\.stfw.*$/}/plugins/${_plugin_name}"
+    if [[ -d "${_real_proj_plugin_dir}" ]]; then
+      _result="${_real_proj_plugin_dir}"
+    fi
   fi
 
   # 組み込みplugin
@@ -580,12 +591,20 @@ function stfw.get_digdag_version() {
 #
 #---------------------------------------------------------------------------------------------------
 function stfw.must_run_on_server() {
-  if [[ "${STFW_PROJ_DIR}" != "${STFW_PROJ_DIR//\/\.stfw//}" ]]; then
-    return ${EXITCODE_SUCCESS}
-  fi
+  if [[ "$(stfw.is_run_on_server)" = "true" ]]; then return ${EXITCODE_SUCCESS}; fi
 
   log.error "must run on server."
   exit ${EXITCODE_ERROR}
+}
+
+function stfw.is_run_on_server() {
+  if [[ "${STFW_PROJ_DIR}" = "${STFW_PROJ_DIR//\/\.stfw//}" ]]; then
+    echo "false"
+    return ${EXITCODE_SUCCESS}
+  fi
+
+  echo "true"
+  return ${EXITCODE_SUCCESS}
 }
 
 #---------------------------------------------------------------------------------------------------
@@ -639,4 +658,130 @@ function stfw.get_raw_params() {
   fi
 
   cat "${_path_params}"
+}
+
+
+function stfw.webhook.async_execute() {
+  local _key="$1"
+  local _type="$2"
+  local _event="$3"
+  local _relpath_plugin="$4"
+
+  # ステータスチェック
+  local _status="success"
+  if [[ "${_event}" = "start" ]]; then
+    _status="started"
+    if [[ "${stfw_webhooks_on_start:?}" != "true" ]]; then return ${EXITCODE_SUCCESS}; fi
+
+  else
+    # check status from digdag
+    # shellcheck disable=SC2154
+    if [[ "${stfw_run_status}" = "error" ]]; then
+      _status="error"
+      if [[ "${stfw_webhooks_on_error:?}" != "true" ]]; then return ${EXITCODE_SUCCESS}; fi
+    else
+      if [[ "${stfw_webhooks_on_success:?}" != "true" ]]; then return ${EXITCODE_SUCCESS}; fi
+    fi
+  fi
+
+  readonly webhook_type=${_type}
+  readonly webhook_status=${_status}
+
+  readonly stfw_raw_params=$(stfw.get_raw_params)
+  readonly STFW_SERVER_VERSION=$(stfw.get_digdag_version)
+
+  # 開始・終了時間計算
+  local _filepath_processing_time=$(private.processing_time.get_filepath "${_key}")
+  local _start_time=$(cat "${_filepath_processing_time}")
+  readonly webhook_start_time=$(timestamp_to_iso ${_start_time})
+
+  local webhook_end_time=
+  local webhook_processing_time=
+  if [[ "${_event}" != "start" ]]; then
+    local _end_time=$(date '+%Y%m%d%H%M%S')
+
+    readonly webhook_end_time=$(timestamp_to_iso ${_end_time})
+    readonly webhook_processing_time=$(private.calc_processing_time ${_start_time} ${_end_time})
+  fi
+
+  # webhookに必要な設定をまとめる
+  local _configs="${DIR_CONFIG}/webhook/payload.yml"
+  case ${_type} in
+    run)
+      _configs="${_configs} ${DIR_CONFIG}/webhook/run.yml"
+      ;;
+    scenario)
+      _configs="${_configs} ${DIR_CONFIG}/webhook/run.yml"
+      _configs="${_configs} ${DIR_CONFIG}/webhook/scenario.yml"
+      ;;
+    bizdate)
+      _configs="${_configs} ${DIR_CONFIG}/webhook/run.yml"
+      _configs="${_configs} ${DIR_CONFIG}/webhook/scenario.yml"
+      _configs="${_configs} ${DIR_CONFIG}/webhook/bizdate.yml"
+      ;;
+    process)
+      _configs="${_configs} ${DIR_CONFIG}/webhook/run.yml"
+      _configs="${_configs} ${DIR_CONFIG}/webhook/scenario.yml"
+      _configs="${_configs} ${DIR_CONFIG}/webhook/bizdate.yml"
+      _configs="${_configs} ${DIR_CONFIG}/webhook/process.yml"
+      ;;
+    *)
+      ;;
+  esac
+
+  local _tmp_yml_file="/tmp/stfw_webhook_${_type}_${_event}_$$.yml"
+
+  # 複数ファイルをcatで合成しつつ、変数展開、jsonへ変換
+  # shellcheck disable=SC2002
+  cat ${_configs} | grep -v "^#" |
+  while IFS= read -r _line; do
+    eval "echo \"${_line}\""
+  done >"${_tmp_yml_file}"
+
+  # プロセスの場合、プラグイン分を合成
+  if [[ ${_type} = "process" ]]; then
+    (
+      # サブシェルとして動かして、カレントディレクトリの移動を意識しなくて良くしています。
+      cd "${stfw_process_dir:?}"
+      local _plugin_dir=$(stfw.get_plugin_path "${_relpath_plugin}")
+      "${_plugin_dir}/bin/webhook/get_${_event}_content" | grep -v "^#" >>"${_tmp_yml_file}"
+      local _retcode=${PIPESTATUS[0]}
+
+      if [[ ${_retcode} -ne ${EXITCODE_SUCCESS} ]]; then
+        log.error "get_${_event}_content is failed. process_relpath_plugin=${_relpath_plugin}"
+      fi
+    )
+  fi
+
+  # 非同期実行
+  private.stfw.webhook_async_execute "${_tmp_yml_file}" &
+}
+
+function private.stfw.webhook_async_execute() {
+  local _tmp_yml_file="$1"
+  local _tmp_json_file="${_tmp_yml_file}.json"
+
+  # yml -> json変換
+  "${DIR_BIN_LIB}/yaml2json" "${_tmp_yml_file}" >"${_tmp_json_file}"
+  rm "${_tmp_yml_file}"
+
+  printenv | grep stfw_webhooks_urls_ | cut -d "=" -f 2 |
+  while read -r _webhooks_url; do
+    curl                                                                                           \
+      --silent                                                                                     \
+      --show-error                                                                                 \
+      --request POST                                                                               \
+      --data-binary "@${_tmp_json_file}"                                                           \
+      --header "Content-type: application/json"                                                    \
+      "${_webhooks_url}" | log.debug
+    _retcode=${PIPESTATUS[0]}
+
+    if [[ ${_retcode} -eq ${EXITCODE_SUCCESS} ]]; then
+      log.info "webhook post to ${_webhooks_url}"
+    else
+      log.warn "webhook post failed. target:${_webhooks_url}, retcode:${_retcode}"
+    fi
+  done
+
+  rm "${_tmp_json_file}"
 }
